# Generated by Django 3.0.5 on 2020-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productespressoshot',
            name='default_quantity',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='flavor_pumps',
        ),
        migrations.AddField(
            model_name='productsize',
            name='default_espresso_shots',
            field=models.PositiveSmallIntegerField(default=0, help_text='default number of espresso shots for the product size'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='default_flavor_pumps',
            field=models.PositiveSmallIntegerField(default=0, help_text='default number of pumps of sauce and syrup for the product size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productsweetener',
            name='default_quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='producttea',
            name='default_quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
