# Generated by Django 3.0.5 on 2020-04-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20200406_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttea',
            old_name='topping',
            new_name='tea',
        ),
        migrations.RemoveField(
            model_name='productsweetener',
            name='default_quantity',
        ),
        migrations.AddField(
            model_name='productsize',
            name='default_tea_quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text='default number of teas for the product size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allowed_ice',
            field=models.ManyToManyField(blank=True, to='coffee.IceChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allowed_milks',
            field=models.ManyToManyField(blank=True, through='coffee.ProductMilk', to='coffee.Milk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allowed_room',
            field=models.ManyToManyField(blank=True, to='coffee.RoomChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allowed_sizes',
            field=models.ManyToManyField(blank=True, through='coffee.ProductSize', to='coffee.Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_espresso_shots',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductEspressoShot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_ice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.IceChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_juices',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductJuice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_milk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.ProductMilk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.RoomChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.ProductSize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_sweeteners',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductSweetener'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_teas',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductTea'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_toppings',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductTopping'),
        ),
    ]
