# Generated by Django 3.0.5 on 2020-04-06 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20200406_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmilk',
            name='allowed_foams',
        ),
        migrations.RemoveField(
            model_name='productmilk',
            name='allowed_temps',
        ),
        migrations.RemoveField(
            model_name='productmilk',
            name='default_foam',
        ),
        migrations.RemoveField(
            model_name='productmilk',
            name='default_temp',
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_milk_foams',
            field=models.ManyToManyField(to='coffee.FoamChoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_milk_temps',
            field=models.ManyToManyField(to='coffee.TempChoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_milk_foam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.FoamChoice'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_milk_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.TempChoice'),
        ),
    ]
