# Generated by Django 3.0.5 on 2020-04-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_auto_20200406_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allowed_milk_foams',
            field=models.ManyToManyField(blank=True, to='coffee.FoamChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allowed_milk_temps',
            field=models.ManyToManyField(blank=True, to='coffee.TempChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_milk_foam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.FoamChoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_milk_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_products', to='coffee.TempChoice'),
        ),
    ]
