# Generated by Django 3.0.5 on 2020-04-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20200406_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_flavors',
            field=models.ManyToManyField(through='coffee.ProductFlavor', to='coffee.Flavor'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_flavors',
            field=models.ManyToManyField(blank=True, related_name='default_products', to='coffee.ProductFlavor'),
        ),
    ]
