# Generated by Django 3.0.5 on 2020-04-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20200406_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflavor',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='productjuice',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='producttea',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='producttopping',
            name='is_default',
        ),
    ]
